version: '3.8'

services:
  backend:
    image: thvnkinger/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mmongodb+srv://cloud_user1:cloud_user1@cluster0.udo3k0s.mongodb.net/mongo-server?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    image: thvnkinger/mern-frontend:2cd .0
    ports:
      - "3000:3000"
    depends_on:
      - backend